// Step 1: Import required modules
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');

// Step 2: Initialize Express app and HTTP server
const app = express();
const server = http.createServer(app);

// Step 3: Initialize Socket.IO on top of the HTTP server (CORS added)
const io = new Server(server, {
    cors: {
        origin: "*",
    }
});

// Step 4: Serve static files from the "public" folder
app.use(express.static(path.join(__dirname, 'public')));

// Track connected users
const users = {};

// Step 5: Handle real-time connections with Socket.IO
io.on('connection', (socket) => {
    console.log('A user connected:', socket.id);

    // Handle user joining
    socket.on('join', (username) => {
        users[socket.id] = username;
        console.log(`${username} joined.`);

        io.emit('system message', `${username} joined the chat`);
        io.emit('user count', Object.keys(users).length);
    });

    // Handle chat messages
    socket.on('chat message', (data) => {
        console.log('Message from ' + data.username + ':', data.text);

        // Broadcast message to everyone (including the sender)
        // Adding msgId so clients can track specific messages
        io.emit('chat message', {
            msgId: data.msgId, // Unique ID generated by client
            username: data.username,
            text: data.text,
            timestamp: new Date().toLocaleTimeString([], {
                hour: '2-digit',
                minute: '2-digit'
            }),
            socketId: socket.id
        });

        // ACKNOWLEDGMENT: Send confirmation back ONLY to the sender
        // This tells the sender the server has received their message
        socket.emit('message delivered', data.msgId);
    });

    // Handle disconnection
    socket.on('disconnect', () => {
        const username = users[socket.id];
        if (username) {
            console.log(`${username} disconnected.`);
            io.emit('system message', `${username} left the chat`);
            delete users[socket.id];

            io.emit('user count', Object.keys(users).length);
        }
    });

    // Initial user count
    socket.emit('user count', Object.keys(users).length);
});

// Step 6: Start the server (Render compatible)
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});